/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    ASpin: typeof import('ant-design-vue/es')['Spin']
    CollaborationModal: typeof import('./src/components/CollaborationModal/CollaborationModal.vue')['default']
    CreateCollaboration: typeof import('./src/components/CreateCollaboration/CreateCollaboration.vue')['default']
    CreatorOperationModal: typeof import('./src/components/CreatorOperationModal/CreatorOperationModal.vue')['default']
    FileList: typeof import('./src/components/FileList/FileList.vue')['default']
    InviteNotify: typeof import('./src/components/ScreenSync/InviteNotify.vue')['default']
    InviteUser: typeof import('./src/components/InviteUser/InviteUser.vue')['default']
    MemberInfo: typeof import('./src/components/ScreenSync/MemberInfo.vue')['default']
    ParticipantModal: typeof import('./src/components/ParticipantModal/ParticipantModal.vue')['default']
    ParticipantOperationPopover: typeof import('./src/components/ParticipantOperationPopover/ParticipantOperationPopover.vue')['default']
    Participants: typeof import('./src/components/Participants/Participants.vue')['default']
    PDFViewer: typeof import('./src/components/PDFViewer/PDFViewer.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    ScreenSync: typeof import('./src/components/ScreenSync/ScreenSync.vue')['default']
    SetCommentPermission: typeof import('./src/components/SetCommentPermission/SetCommentPermission.vue')['default']
    SetPublicPermission: typeof import('./src/components/SetPublicPermission/SetPublicPermission.vue')['default']
    TopNav: typeof import('./src/components/TopNav/TopNav.vue')['default']
  }
}
